### PR TITLE
Fix #2715

### LINKED ISSUE #2715: [Repository][UI] 'Завантажити додаток' button is not displayed on the сenter of the 'Додатки' column
**Environment:** Windows 10 Pro, Google Chrome version 103.0.5060.114 (development)(64-bit).
**Reproducible:** always.
**Build found:** last commit from [eee869f](https://github.com/ita-social-projects/EPlast/commit/eee869f9c689117261a1df72a159073cf5b4f5be)
**Priority**: low
**Severity**: low

**Preconditions**
Sign in as a superadmin (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**

1. Go to the left-side menu
2. Click on 'Довідник'
3. Go to the 'Repository' 
4. Click on any tab ("Нормативні акти", "Методичні документи", "Різне")
5. Verify the alignment of the "Завантажити додаток" button in the "Додатки" column

**Actual result**
The alignment of the "Завантажити додаток" button in the "Додатки" column is not correct, it is in the left part of the column.
button alignment

**Expected result**
The alignment of the "Завантажити додаток" button in the "Додатки" column should be in the center.

### PR DESCRIPTION
**Pull request by Mykola123-NMT**
closes https://github.com/ita-social-projects/EPlast/issues/2715

### CODE REVIEW

File: src/pages/Documents/columns.tsx [hunk 1]
```diff
@@ -40,6 +40,7 @@ const columns = [
   {
     title: "Додатки",
     dataIndex: "fileName",
+    align: 'center' as const,
```
Comment (gutovskii) [inline src/pages/Documents/columns.tsx:43]: Why did you write "as const"? I'm wondering)

**Review by gutovskii — APPROVED** [review]

**Review by MishaHMK — APPROVED** [review]

**Review by IrynaZavushchak — APPROVED** [review]

File: src/pages/Documents/columns.tsx (hunk 1 above)
Comment (Mykola123-NMT) [reply src/pages/Documents/columns.tsx:43]: got the same problem as here https://stackoverflow.com/questions/61519622/antd-with-typescript-table-with-column-align-right-is-not-compiling
